# Np2d examples

In [1]:
import numpy as np
import np2d

## `random.choice`

In [21]:
a = np.random.uniform(0,10, size=(3,4)) 

# Construct a probability array
p = np.random.random(size=(3,4))
p = p/p.sum()
print(" A array:")
print(a)
print("\n Probability array:")
print(p)

 A array:
[[ 6.66750293  7.41613631  3.06095927  6.2575966 ]
 [ 0.09117781  5.76947021  4.74042123  8.26263678]
 [ 6.90855765  1.34674523  3.72345305  7.21179911]]

 Probability array:
[[ 0.03845405  0.0050683   0.09646995  0.17584875]
 [ 0.11606853  0.12240921  0.17354756  0.14188227]
 [ 0.00461633  0.01130194  0.01756229  0.09677082]]


In [22]:
vals, coor = np2d.random.choice2d(a, size=4, p=p)
print(" Samples:")
print(vals)
print(" Indices:")
print(coor)

 Samples:
[ 8.26263678  1.34674523  8.26263678  0.09117781]
 Indices:
[[1 3]
 [2 1]
 [1 3]
 [1 0]]
