# Np2d examples

In [1]:
import numpy as np
import np2d

## `random.choice`

In [2]:
a = np.random.uniform(0,10, size=(3,4)) 

# Construct a probability array
p = np.random.random(size=(3,4))
p = p/p.sum()
print(" A array:")
print(a)
print("\n Probability array:")
print(p)

 A array:
[[ 8.12730301  3.17969548  5.1463011   1.21137116]
 [ 4.79779323  1.7580591   1.42487239  2.37899759]
 [ 4.59841327  0.75811371  8.32494328  4.77565214]]

 Probability array:
[[ 0.05264463  0.09225875  0.14023031  0.12928219]
 [ 0.14348546  0.09416479  0.04194738  0.08579122]
 [ 0.06108743  0.03364044  0.03656878  0.08889862]]


In [3]:
vals, coor = np2d.random.choice(a, size=4, p=p)
print(" Samples:")
print(vals)
print(" Indices:")
print(coor)

 Samples:
[ 4.79779323  2.37899759  2.37899759  1.7580591 ]
 Indices:
[[1 0]
 [1 3]
 [1 3]
 [1 1]]
